version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
        environment:
          - "discovery.type=single-node"
          - "cluster.name=solr2es"
          - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        name: elasticsearch
      - image: solr:6.6.0
        name: solr
      - image: redis:4.0.1-alpine
        name: redis
      - image: postgres:10.4
        name: postgresql
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: solr2es

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            python setup.py develop 

      - run:
          name: create solr core
          command: curl "http://solr:8983/solr/admin/cores?action=CREATE&name=test_core&instanceDir=/opt/solr/server/solr/configsets/basic_configs/"

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install -e ".[dev]"
            python setup.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
